### ISSUE TITLE
Please upload the problem statement word document that geeta madam presented in last class

### ISSUE THREAD

**Issue by 123mw123** [raghavsi/elv781-2019#5]

**Comment by raghavsi** [comment]
sent a mail on Monday, did that suffice?
all material on GitHub

**Comment by geetasinghbhati** [comment]
It is uploaded as a pdf document Project_6_3_2019. As noted in an email from Raghav, we have narrowed down and detailed the home work assignment as described in the word document "Instructions for the Project" which has also been put on the page.

**Comment by 123mw123** [comment]
Ok Thanks
