### ISSUE TITLE
Please clarify variables linked to columns in data

### ISSUE THREAD

**Issue by aasavari** [raghavsi/elv781-2019#6]
It is difficult to understand which abbreviation corresponds to which variable. 
Kindly clarify on this. Thank you!

**Comment by raghavsi** [comment]
Is this from the list in instructions? or from the data itself? please clarify and we will help

**Comment by aasavari** [comment]
from data itself.

**Comment by geetasinghbhati** [comment]
I have uploaded  instructions for reading in the data.
