### ISSUE TITLE
exact problem statement

### ISSUE THREAD

**Issue by nishant1212112** [raghavsi/elv781-2019#8]
Sir/Ma'am,
Can you please specify if we have to exactly replicate the findings  in first part  and as there are too many conditions used to get to it.for example they are using 21 - 35 age group data which isnt mentioned in problem statement .

**Comment by geetasinghbhati** [comment]
Yes, the OLS results have to be replicated . Project description indicates which Census sample to use but paper will tell you exact selection. Check against the descriptive statistics table to see if you have implemented the right sample.

**Comment by nishant1212112** [comment]
Ma'am 
I tried to replicate the findings but i m not getting the numbers to be exact they are slightly more /less then the ones mentioned in the report. can you please confirm if anyone is getting the exact same results. That might be the case they have not mentioned all the conditions .

**Comment by geetasinghbhati** [comment]
Don't worry about that. Report whatever you have Raghav will post work product instructions.
